### ISSUE TITLE
High cpu consumption after first login

### ISSUE THREAD

**Issue by mromanbanks** [lbrndnr/nuage-macos#1]
After a first login the app is very glitchy and unusable. CPU consumption goes over 100% so I had to force quit the app. On second launch things are better, but sometimes I see sparks up to 60%. MBP 13' 2020 base specs

**Comment by lbrndnr** [comment]
I observed this too and I must admit that I have no idea where this comes from and also don't really know how to debug this issue. I'm not even certain whether this is a bug in SwiftUI or in my implementation...

**Comment by alex-taffe** [comment]
Same issue here

**Comment by alex-taffe** [comment]
I can help debug this but need some feedback on #3 first

**Comment by lbrndnr** [comment]
As I said, I have little to no clue where this comes from. I noticed however that the profile images sometimes cause a memory spike (that's why I changed the image loading framework from sdwebimage to urlimage, this seemed to help). In particular the profile image in the toolbar seemed to make a big difference, again, no idea why.
It's also possible that the InfiniteList view causes the lagging, too, so maybe checking this out could help as well :)

**Comment by alexkaessner** [comment]
+1 from my side. I’ve noticed that as soon as I start using the app – scrolling around or clicking on the navigation – the app renders itself practically unusable. It’s responding super slow and the system declares it as „not responding“, though it eventually reacts to some clicks. Just _very_ slow (the GIF is not cut in any way):

![Screen recording](https://user-images.githubusercontent.com/6615076/106352749-eb523c00-62e5-11eb-9cd5-50cb021da636.gif)

PS: I’m running the [v0.0.1-alpha](https://github.com/lbrndnr/nuage-macos/releases/tag/v0.0.1-alpha) on macOS 11.1

**Comment by lbrndnr** [comment]
@alexkaessner do you experience this issue only after login or in general?

**Comment by alexkaessner** [comment]
@lbrndnr Always. I've restarted the app a few times, but the issue still appears.

**Comment by lbrndnr** [comment]
Hmm damn that's a shame. Would be interesting to see if it made a difference for you if you removed the profile images (e.g. returned EmptyView in RemoteImage in the Externals file)

**Comment by lbrndnr** [comment]
Ok, SwiftUI's slider seems to be the problem that causes lots of unnecessary renders. I'm now writing a custom slider view, which will be necessary for nicer UI anyways. Would be great if this fixes the problem for you too :) The code can be found in the [slider](/lbrndnr/nuage-macos/tree/slider) branch. Note that the sliders are now lacking some functionality which I will implement in the coming days

**Comment by lbrndnr** [comment]
@alexkaessner @mromanbanks Could you check whether the latest commits improve the CPU footprint a little?

**Comment by mromanbanks** [comment]
@lbrndnr Can you please publish compiled version for the app? 🙏

**Comment by lbrndnr** [comment]
@mromanbanks done

**Comment by mromanbanks** [comment]
Now it's better. Still see spikes up to 60% when scrolling feed/album for the first time, but app is usable 👍

**Comment by lbrndnr** [comment]
@mromanbanks ok great, I think I just gotta dig out these little quirks to make it more lightweight. But glad it's usable for now.
