### ISSUE TITLE
Can't shuffle / repeat

### ISSUE THREAD

**Issue by jpike88** [lbrndnr/nuage-macos#15]
Shuffle is a big way I play from my 'liked' list, its a shame this isn't present

**Comment by lbrndnr** [comment]
<img width="295" alt="Screenshot 2023-08-12 at 11 00 33" src="https://github.com/lbrndnr/nuage-macos/assets/762049/74c7af98-2b5c-41e5-9a20-d9d29d1add5a">
Don't know how to add this to the UI without making it completely cluttered, but it's working :)
