### ISSUE TITLE
Search bar does not load as you type 

### ISSUE THREAD

**Issue by riverray121** [lbrndnr/nuage-macos#19]
When using the search feature only the first thing entered on the search bar is searched for (most of the time this is the first letter of the word you type). 

Manual workaround to see the problem clearer is to copy paste the word / name you would like to search into the search bar rather than typing it (this causes it to show results for the entire word you are looking to search) :)

**Comment by lbrndnr** [comment]
Thanks for your feedback! The search bar is not super functional right now. I'm planning on integrating [SearchField](https://github.com/lbrndnr/SearchField) some time soon, though :)

**Comment by lbrndnr** [comment]
Fixed in 02a10a50 :)
