### ISSUE TITLE
Not obvious how to play tracks

### ISSUE THREAD

**Issue by mromanbanks** [lbrndnr/nuage-macos#2]
I was frustrated to figure out how to start listening tracks. There is no Play button anywhere. The only way is to Right Click/Play. I think nice to have a Play button on the track cover

**Comment by lbrndnr** [comment]
Yes, I agree :) You can also double click the tracks, though this seems to conflict with the single click gesture. I was thinking of adding a play button on top of the artwork instead of the double click, though.

**Comment by lbrndnr** [comment]
I have addressed this issue in the latest commits. Certainly not very nice UI just yet, but seems to be working. Closing this for now :)
