### ISSUE TITLE
output control

### ISSUE THREAD

**Issue by danaenayati** [lbrndnr/nuage-macos#20]
Hi
Users can not control the output of the sound. it would be great if users could manage sound output, for example airplay or external speakers.

**Comment by lbrndnr** [comment]
Thanks for your feature request, but I don't think I will add this in the near future. You can just change the global music output.

**Comment by saulhoward** [comment]
Thanks for the app, it's awesome! I wonder if you would reconsider this feature -- I find it an important feature of e.g. the Apple Music macos app that you can send it to AirPlay outside of global sound settings. It lets this app control "music playback to external speakers" while you use other apps at the same time.

**Comment by lbrndnr** [comment]
It would be a useful feature, that's for sure! However, I won't have much time working on this project in the future, so I guess I will mostly focus on bug fixes and small but important features. 
However, you could definitely fork this project and work on this feature on your own, I'd be happy to help!

**Comment by saulhoward** [comment]
Totally understand. If I ever get into Swift dev I might give it a shot. Until then, thanks for the app!
