### ISSUE TITLE
Playlists do not work correctly

### ISSUE THREAD

**Issue by Finorion** [lbrndnr/nuage-macos#21]
Hi) 
Thank you so much for such a great app. 

I noticed the playlist didn't work correctly

<img width="1313" alt="Снимок экрана 2023-07-06 в 12 45 24" src="https://github.com/lbrndnr/nuage-macos/assets/3991341/5583828c-a10c-4277-91f3-f72992418b6c">

**Comment by lbrndnr** [comment]
Thanks for your feedback! I will look into this, haven't encountered it myself :)

**Comment by lbrndnr** [comment]
This should be fixed in 6f4c193 :)
