### ISSUE TITLE
Nuage crashes on macOS Sonoma

### ISSUE THREAD

**Issue by jamesf-hub** [lbrndnr/nuage-macos#26]
Nuage crashes (latest version) of macOS Sonoma beta (3)

**Comment by lbrndnr** [comment]
Thanks for your feedback! Can you provide me with a crash log? :)

**Comment by lbrndnr** [comment]
It's possible that I actually have fixed this in the latest commit. Could you quickly compile the latest commit to check? Or alternatively, the crash log could help as well :)

**Comment by lbrndnr** [comment]
I have just released a new version that fixes a crash upon login. Could you quickly verify that 0.0.5 fixes this? :)

**Comment by jamesf-hub** [comment]
yes, sorry i forgot to upload the crash logs

**Comment by jamesf-hub** [comment]
thank you

**Comment by lbrndnr** [comment]
So just to clarify, doesnit fixes the crash?
