### ISSUE TITLE
After signing into SoundCloud the authentication window persists

### ISSUE THREAD

**Issue by marcoroth** [lbrndnr/nuage-macos#28]
Hey 👋🏼 

Thanks for building this app!

I'm not sure if I'm doing something wrong (which could totally be the case here) but after signing into SoundCloud in the WebView it just redirects me back to the regular website inside the WebView. I suppose it's meant to show the native version of the app instead.

Is there something I'm overseeing?

I'm assuming that the redirect back to the Native App somehow along the way doesn't work.

https://github.com/lbrndnr/nuage-macos/assets/6411752/2beb6892-5bc5-411e-94f8-8852744ed182

FWIW this was happening on 0.0.4 and is also happening on the new 0.0.5 version.

Let me know if I can provide any more insights which could help to pinpoint the issue.

**Comment by lbrndnr** [comment]
Thanks for your feedback! Once you log in, the app should turn on. So somehow, in your case it fails to retrieve the access token. I'll have a look :)

**Comment by lbrndnr** [comment]
@marcoroth if you have the time you could quickly compile the project and print the cookie names that are retrieved in [WebView](https://github.com/lbrndnr/nuage-macos/blob/c37f27cce9136892d08230277243ca8c63a09944/Nuage/Views/WebView.swift#L56). There should be one called `oauth_token`, but maybe there are other names or some other mechanism? Or the function is just not called?

**Comment by marcoroth** [comment]
It just prints the `oauth_token` cookie like 7 times. 

But I also just found out when I Cmd-click on the WebView after I signed in and click on "Reload" in the context menu it works as expected and brings up the native app. 

But seems like there is no explicit logout functionality to try it again 🙈

**Comment by lbrndnr** [comment]
hahah true, maybe I should add this too ;) You can logout using `defaults delete ch.laurinbrandner.nuage`. Could you quickly check if the cookie is sometimes set to `nil`? Then a fix would simply consist of checking for `nil` first :)

**Comment by marcoroth** [comment]
Okay, actually no. `oauth_token` is not logged until I reload the WebView. On the first load after signing in I get: 
```
datadome
datadome
_soundcloud_session
datadome
connect_session
soundcloud_session_hint
```

Reloading the WebView then shows the `oauth_token` cookie:
```
_soundcloud_session
oauth_token
datadome
connect_session
soundcloud_session_hint
ajs_user_id
ajs_anonymous_id
ja
```

Are you signing in with any third-party service yourself or are you also using a SoundCloud login?

**Comment by marcoroth** [comment]
And I think I also know why it's happening. If you are singing in via https://soundcloud.com/signin it's not re-requesting the page from the server again. All of the sign-in logic is client-side routed, which means the cookies are not going to get set until the next request gets served from the server-side.

It's weird, because the behavior is different when you go to https://soundcloud.com and then click on sign-in. It's doing a redirect after the sign-in which then properly re-requests the page from the server-side which then has all the cookies properly set.

**Comment by marcoroth** [comment]
Okay, I think I might have found _a_ solution for this in https://github.com/lbrndnr/nuage-macos/pull/29. I'm not sure if this is too hacky, but it seems to resolve the issue reliably in my case.

**Comment by lbrndnr** [comment]
The thing is that SoundCloud has stopped handing out client tokens. This is the most user friendly way I came up with in order to retrieve an access token nevertheless. So I'm prepared for it to get a bit hacky ;)
