### ISSUE TITLE
Option to show only "Created" Playlists in the sidebar

### ISSUE THREAD

**Issue by codeanpeace** [lbrndnr/nuage-macos#30]
Regarding the playlists, there are two types of playlists on SoundCloud – those that you created yourself and those that you liked from others. If you visit [https://soundcloud.com/you/sets](https://soundcloud.com/you/sets), you'll see a dropdown on the right that defaults to "All" but also offers "Liked" and "Created" as options. It'd be nice if nuage could build in that distinction as I'd much rather only see those that I created myself. While I've only created a dozen or so playlists, I've liked countless of other artists' and users' playlists/albums/sets. Hope this helps!

_Originally posted by @codeanpeace in https://github.com/lbrndnr/nuage-macos/issues/27#issuecomment-1643222643_

**Comment by lbrndnr** [comment]
<img width="391" alt="Screenshot 2023-08-11 at 21 02 14" src="https://github.com/lbrndnr/nuage-macos/assets/762049/726f9604-e91d-475f-ad6a-aa256681e423">
Fixed :)
