### ISSUE TITLE
Contents of the stream tab remain empty

### ISSUE THREAD

**Issue by codeanpeace** [lbrndnr/nuage-macos#31]
The contents of the stream tab remain empty – screenshot attached

<img width="845" alt="image" src="https://github.com/lbrndnr/nuage-macos/assets/2991389/063806ba-6674-46e2-b318-db53fdb975a1">

_Originally posted by @codeanpeace in https://github.com/lbrndnr/nuage-macos/issues/27#issuecomment-1643210189_

**Comment by lbrndnr** [comment]
Hmm this is weird. Are the things like likes and history working? I'm assuming this is not working for v0.0.6, right?

**Comment by lbrndnr** [comment]
Fixed this in the latest commit. Noticed that soundcloud returns empty pages ¯\_(ツ)_/¯
