### ISSUE TITLE
Crash 0.0.5

### ISSUE THREAD

**Issue by RuslanShah** [lbrndnr/nuage-macos#34]
Hello!

Updated version to 0.0.5
Crash on the launch :(

MacOs 13.4.1 (c) (22F770820d)

<img width="273" alt="Screenshot 2023-07-29 at 15 42 27" src="https://github.com/lbrndnr/nuage-macos/assets/129128156/6036652c-6c12-43f6-889a-133d98873042">

[log.txt.zip](https://github.com/lbrndnr/nuage-macos/files/12207171/log.txt.zip)

**Comment by lbrndnr** [comment]
Thanks for your feedback! Weird, I though I fixed this issue some time ago, not sure why this is still a problem. Will look into it!

**Comment by lbrndnr** [comment]
Do you mind testing the latest release real quick? :)

**Comment by RuslanShah** [comment]
> 

Hi, I don't know how to build: )) Open a project in xcode?

**Comment by lbrndnr** [comment]
You can download the latest release [here](https://github.com/lbrndnr/nuage-macos/releases/tag/v0.0.6).

**Comment by RuslanShah** [comment]
> You can download the latest release [here](https://github.com/lbrndnr/nuage-macos/releases/tag/v0.0.6).

Yea, it's working. Tnx!

**Comment by lbrndnr** [comment]
Perfect :)
