### ISSUE TITLE
Brew support

### ISSUE THREAD

**Issue by marcoroth** [lbrndnr/nuage-macos#4]
Hey Laurin, very cool project! 

It would be awesome to have Nuage also available on Homebrew for easy installation 😊 

The process should be very straight-forward: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

Thanks!

**Comment by lbrndnr** [comment]
Marco! Thank you :)
I would love to make a homebrew formula for Nuage but I don't have an Apple developer ID right now to codesign the app. I'll wait a little longer until the app gains some more traction and ideally a few sponsors until I buy the license. In the mean time you can download new releases from [here](https://github.com/lbrndnr/nuage-macos/releases).

**Comment by marcoroth** [comment]
Awesome!

I don't think you need a developer license to publish on brew. Or do you mean to sign the `.app` itself? But then you would have the same problem if somebody just downloads it from GitHub 😅 

Either way, here is how the formula would look like and it works perfectly fine locally. You can create the formula with this command (`brew create --cask download-url --set-name nuage`) and then paste the following:

```ruby
cask "nuage" do
  version "v0.0.1-alpha.2"
  sha256 "59236ec62ad99ce977e2c470cba0d759ff651138963c3173630442282997d3b8"

  url "https://github.com/lbrndnr/nuage-macos/releases/download/#{version}/Nuage.zip"
  name "Nuage"
  desc "A native SoundCloud app for macOS, written in SwiftUI"
  homepage "https://github.com/lbrndnr/nuage-macos"

  depends_on macos: ">= :big_sur"

  app "Nuage.app"
end
```

I can then successfully itself your app with `brew install nuage`.

The only thing which would block it as of right now is the audit (`brew audit --cask --new nuage`), which states:
```
audit for nuage: failed
 - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
 - v0.0.1-alpha.2 is a GitHub pre-release.
Error: 2 problems in 1 cask detected
```

**Comment by lbrndnr** [comment]
Oh okay, guess we gotta wait a little anyways then :)

**Comment by lbrndnr** [comment]
Nuage is now available on homebrew :) thanks for helping out!

**Comment by marcoroth** [comment]
Awesome! 🎉
