### ISSUE TITLE
Code-Signing

### ISSUE THREAD

**Issue by SENTINELITE** [lbrndnr/nuage-macos#42]
Hey, there!

I've been keeping a keen eye on this project for a few years. Curious if there's any plans to code-sign the app, as it's being prevented from running on macOS.

<img width="372" alt="Screenshot 2024-01-27 at 3 53 40 PM" src="https://github.com/lbrndnr/nuage-macos/assets/44782976/3cf56d02-563d-478f-8953-3cad2b372af3">

**Comment by lbrndnr** [comment]
I don't have an Apple Developer account anymore, so I can't sign it for you to run it without this alert. But if you follow [these instructions](https://support.apple.com/en-us/HT202491), you can open it anyways :)
