### ISSUE TITLE
App crash on open

### ISSUE THREAD

**Issue by 3DJakob** [lbrndnr/nuage-macos#5]
I opened the app and was greeted with the login page. Once I had filled in my information and pressed login the app crashed. Every time I open it, it just instantly crashes.

Running nuage version 0.0.1 on Macbook Air M1. I have tried launching the app both with rosetta and without with the same result.

Do you have any idea how to solve this?  Let me know if I can help with any specific data or so.

**Comment by lbrndnr** [comment]
Could you provide me with the crash report? You can find it in the Console app :)

**Comment by jpinnix** [comment]
Same experience on my 2020 non-M1 Macbook Pro

[Nuage_2021-02-24-163009_obfuscated.crash.txt](https://github.com/lbrndnr/nuage-macos/files/6039260/Nuage_2021-02-24-163009_obfuscated.crash.txt)

**Comment by lbrndnr** [comment]
Ok got it, think I know the problem. Will try fixing it tmrw :)

**Comment by chrismessina** [comment]
Same for me (after I signed in w/ my password).

[nuage-crash.txt.zip](https://github.com/lbrndnr/nuage-macos/files/6039596/nuage-crash.txt.zip)

**Comment by lbrndnr** [comment]
Fixed this in 723745a78c456ca125207ccd5db0dd837659c11a. Should be working with the next release :)
