### ISSUE TITLE
Please enable popups to allow 3rd party authentication

### ISSUE THREAD

**Issue by chrismessina** [lbrndnr/nuage-macos#6]
I'm unable to sign in with third party providers because popups aren't enabled:

![image](https://user-images.githubusercontent.com/22610/109083082-11d37f00-76ba-11eb-9c14-f4c8de31dbbd.png)

**Comment by lbrndnr** [comment]
Which service did you try to login with?

**Comment by nateansel** [comment]
I just tried this with Facebook and it failed for the reason shown above.

Additionally, clicking on any of the alternate sign in methods (Facebook, Google, and Apple) all show the same message about pop-up blockers.

**Comment by lbrndnr** [comment]
Fixed this in the latest release, version 0.0.2. Could you please download that version and try it again? :)

**Comment by nateansel** [comment]
Version `0.0.2` works beautifully, thanks so much for the help! 😃

**Comment by lbrndnr** [comment]
Perfect, glad it works :)
