### ISSUE TITLE
Stream is empty after first launch

### ISSUE THREAD

**Issue by chrismessina** [lbrndnr/nuage-macos#8]
I was able to sign into my account, but my Stream is completely blank after first launch:

![image](https://user-images.githubusercontent.com/22610/109235162-f8960580-7781-11eb-8a65-7484f88771ea.png)

Other screens populate correctly. 

After quitting and restarting the app, my Stream populated as expected.

**Comment by artemartemov** [comment]
same issue here, but doesn't seem to populate even after a restart

**Comment by chrismessina** [comment]
@artemartemov I'm going to presume this is abandonware. It hasn't been updated in 7 months.

**Comment by lbrndnr** [comment]
@chrismessina I'm actually still working on this, I've just been super busy the last couple of months... But I want to release a new update sometime soon

**Comment by chrismessina** [comment]
> @chrismessina I'm actually still working on this, I've just been super busy the last couple of months... But I want to release a new update sometime soon

Ok, fair enough! Just haven't seen any updates on some pretty big issues. Glad to hear you're still on it!

**Comment by lbrndnr** [comment]
SwiftUI is also a bit of a pain to work with, some issues I think are pretty difficult to solve. Also performance is super bad without any very obvious reasons. So I'm hoping the next version of SwiftUI will make things easier too.

**Comment by lbrndnr** [comment]
This should work better now :)
